spring:
  application:
    name: movie-api
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

tmdb:
  api:
    key: ${TMDB_API_KEY:your_tmdb_api_key}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
  packages-to-scan: com.matteodcr.movieapi

management:
  endpoints:
    web:
      cors:
        allowed-origins: ${ALLOWED_ORIGINS:*}

server:
  error:
    include-stacktrace: never

